import{jsx as _jsx}from"react/jsx-runtime";import{useEffect,useRef,useCallback,useMemo}from"react";import{addPropertyControls,ControlType,useIsStaticRenderer}from"framer";// --- Helpers ---
function parseColor(col){if(col.startsWith("#")){let hex=col.slice(1);if(hex.length===3){hex=hex.split("").map(c=>c+c).join("");}return{r:parseInt(hex.slice(0,2),16),g:parseInt(hex.slice(2,4),16),b:parseInt(hex.slice(4,6),16)};}else if(col.startsWith("rgb")){const m=col.match(/\d+/g);return m?{r:+m[0],g:+m[1],b:+m[2]}:{r:0,g:0,b:0};}return{r:0,g:0,b:0};}export default function MouseTrail(props){const{variant="line",fillType="solid",trailColor="#0099FF",trailColorEnd="#FF00FF",trailLength=20,lineWidth=3,fadeOut=true,smoothing=.3,dotSize=6,dotSpacing=10,particleCount=6,particleSize=3,spreadAngle=30,drift=.4,pixelSize=6,snapToGrid=true,blendMode="source-over",autoFade=true,fadeDuration=2,style}=props;const canvasRef=useRef(null);const containerRef=useRef(null);const trailPointsRef=useRef([]);const particlesRef=useRef([]);const rafRef=useRef();const isStatic=useIsStaticRenderer();const timeRef=useRef(performance.now());// --- Color Logic ---
const baseRGBStart=useMemo(()=>parseColor(trailColor),[trailColor]);const baseRGBEnd=useMemo(()=>parseColor(trailColorEnd),[trailColorEnd]);const rgba=useCallback((a,t)=>{if(fillType==="gradient"){const r=baseRGBStart.r+(baseRGBEnd.r-baseRGBStart.r)*t;const g=baseRGBStart.g+(baseRGBEnd.g-baseRGBStart.g)*t;const b=baseRGBStart.b+(baseRGBEnd.b-baseRGBStart.b)*t;return`rgba(${r},${g},${b},${Math.max(0,Math.min(1,a))})`;}return`rgba(${baseRGBStart.r},${baseRGBStart.g},${baseRGBStart.b},${Math.max(0,Math.min(1,a))})`;},[baseRGBStart,baseRGBEnd,fillType]);// Reset particles on variant change
useEffect(()=>{if(variant!=="particles")particlesRef.current=[];},[variant]);const localToCanvas=useCallback((clientX,clientY)=>{const canvas=canvasRef.current;if(!canvas)return{x:0,y:0};const rect=canvas.getBoundingClientRect();return{x:clientX-rect.left,y:clientY-rect.top};},[]);// --- Core Logic ---
const addPoint=useCallback((x,y)=>{const points=trailPointsRef.current;const last=points[points.length-1];// Debounce dots based on spacing
if(variant==="dots"&&last){const dx=x-last.x;const dy=y-last.y;if(Math.hypot(dx,dy)<dotSpacing)return;}// Smoothing
const s=Math.max(.001,1-smoothing);const sx=last?last.x+(x-last.x)*s:x;const sy=last?last.y+(y-last.y)*s:y;points.push({x:sx,y:sy,life:1});// Trim length
if(points.length>trailLength){points.splice(0,points.length-trailLength);}// Spawn particles
if(variant==="particles"&&last){const dx=sx-last.x;const dy=sy-last.y;const speed=Math.hypot(dx,dy);if(speed>2){const angle=Math.atan2(dy,dx);const spread=spreadAngle*Math.PI/180;for(let i=0;i<particleCount;i++){const a=angle+(Math.random()-.5)*spread;const v=speed*.1+Math.random()*2;particlesRef.current.push({x:sx,y:sy,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.8+Math.random()*.4,size:particleSize+Math.random()*1.5});}}}},[trailLength,smoothing,variant,dotSpacing,particleCount,particleSize,spreadAngle]);const drawFrame=useCallback(dt=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.globalCompositeOperation=blendMode;const rect=canvas.getBoundingClientRect();ctx.clearRect(0,0,rect.width,rect.height);const points=trailPointsRef.current;// 1. Age points
if(autoFade&&points.length){const decay=dt/Math.max(.001,fadeDuration);for(let i=points.length-1;i>=0;i--){points[i].life-=decay;if(points[i].life<=0)points.splice(i,1);}}if(points.length<1)return;// Helper for fade-along-path
const indexAlpha=(i,n)=>{if(!fadeOut)return 1;const t=n<=1?1:i/(n-1);return 1-(1-t)*(1-t);};// 2. Render Variants
if(variant==="dots"){for(let i=0;i<points.length;i++){const p=points[i];const t=i/(points.length-1||1);const a=indexAlpha(i,points.length)*(autoFade?p.life:1);const r=dotSize*(fadeOut?.3+.7*a:1);ctx.fillStyle=rgba(a,t);ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();}}else if(variant==="pixel"){for(let i=0;i<points.length;i++){let{x,y}=points[i];if(snapToGrid){x=Math.round(x/pixelSize)*pixelSize;y=Math.round(y/pixelSize)*pixelSize;}const t=i/(points.length-1||1);const a=indexAlpha(i,points.length)*(autoFade?points[i].life:1);const s=pixelSize*(fadeOut?.6+.4*a:1);ctx.fillStyle=rgba(a,t);ctx.fillRect(x-s/2,y-s/2,s,s);}}else if(variant==="particles"){const particles=particlesRef.current;const decayPerSec=1.6;const gravityPerSec=drift*60*.001;const dampingPerSec=.98;const damping=Math.pow(dampingPerSec,dt*60);const g=gravityPerSec*dt*60;const decay=decayPerSec*dt;// Update particles
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.vx*=damping;p.vy=p.vy*damping+g;p.life-=decay;if(p.life<=0){particles.splice(i,1);}else{ctx.fillStyle=rgba(p.life,1-p.life);ctx.beginPath();ctx.arc(p.x,p.y,p.size*p.life,0,Math.PI*2);ctx.fill();}}// Draw connecting lines
if(points.length>1){for(let i=1;i<points.length;i++){const p1=points[i-1];const p2=points[i];const lifeFactor=autoFade?points[i].life:1;const a=.15*indexAlpha(i,points.length)*lifeFactor;ctx.strokeStyle=rgba(a,i/(points.length-1||1));ctx.lineWidth=Math.max(1,lineWidth*.5*a);ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke();}}}else{// Default: Line
if(points.length<2){const p=points[0];const a=autoFade?p.life:1;ctx.fillStyle=rgba(a,0);ctx.beginPath();ctx.arc(p.x,p.y,Math.max(1,lineWidth/2),0,Math.PI*2);ctx.fill();return;}for(let i=1;i<points.length;i++){const p1=points[i-1];const p2=points[i];const t=i/(points.length-1||1);const lifeFactor=autoFade?points[i].life:1;const a=indexAlpha(i,points.length)*lifeFactor;const widthScale=fadeOut?.3+.7*a:1;ctx.strokeStyle=rgba(a,t);ctx.lineWidth=Math.max(1,lineWidth*widthScale);ctx.beginPath();ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke();}}},[variant,fadeOut,rgba,lineWidth,dotSize,drift,blendMode,pixelSize,snapToGrid,autoFade,fadeDuration]);const animate=useCallback(()=>{const now=performance.now();let dt=(now-timeRef.current)/1e3;dt=Math.max(0,Math.min(dt,.05))// Cap delta time
;timeRef.current=now;drawFrame(dt);rafRef.current=requestAnimationFrame(animate);},[drawFrame]);// --- Effects ---
useEffect(()=>{if(isStatic)return;const canvas=canvasRef.current;const container=containerRef.current;if(!canvas||!container)return;const ctx=canvas.getContext("2d");if(!ctx)return;const resize=()=>{const rect=canvas.getBoundingClientRect();const dpr=window.devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(1,0,0,1,0,0);ctx.scale(dpr,dpr);trailPointsRef.current=[];};resize();window.addEventListener("resize",resize);const handlePointerMove=e=>{const containerRect=container.getBoundingClientRect();if(e.clientX>=containerRect.left&&e.clientX<=containerRect.right&&e.clientY>=containerRect.top&&e.clientY<=containerRect.bottom){const{x,y}=localToCanvas(e.clientX,e.clientY);addPoint(x,y);}};const handlePointerDown=handlePointerMove;document.addEventListener("pointermove",handlePointerMove,{passive:true});document.addEventListener("pointerdown",handlePointerDown,{passive:true});timeRef.current=performance.now();rafRef.current=requestAnimationFrame(animate);return()=>{window.removeEventListener("resize",resize);document.removeEventListener("pointermove",handlePointerMove);document.removeEventListener("pointerdown",handlePointerDown);if(rafRef.current)cancelAnimationFrame(rafRef.current);};},[animate,addPoint,isStatic,localToCanvas]);// Intrinsic fallback
const w=props?.width??800;const h=props?.height??600;return /*#__PURE__*/_jsx("div",{ref:containerRef,style:{...style,width:"100%",height:"100%",minWidth:w,minHeight:h,position:"relative",pointerEvents:"none"},children:/*#__PURE__*/_jsx("canvas",{ref:canvasRef,style:{position:"absolute",inset:0,width:"100%",height:"100%",pointerEvents:"none"}})});}MouseTrail.defaultProps={width:800,height:600};addPropertyControls(MouseTrail,{variant:{type:ControlType.Enum,title:"Style",options:["line","dots","particles","pixel"],optionTitles:["Line","Dots","Particles","Pixel"],defaultValue:"line"},fillType:{type:ControlType.Enum,title:"Fill",options:["solid","gradient"],optionTitles:["Solid","Gradient"],defaultValue:"solid"},trailColor:{type:ControlType.Color,title:"Color",defaultValue:"#0099FF"},trailColorEnd:{type:ControlType.Color,title:"Color end",defaultValue:"#FF00FF",hidden:p=>p.fillType!=="gradient"},trailLength:{type:ControlType.Number,title:"Trail length",defaultValue:20,min:5,max:120},lineWidth:{type:ControlType.Number,title:"Line width",defaultValue:3,min:1,max:20,hidden:p=>p.variant==="pixel"},fadeOut:{type:ControlType.Boolean,title:"Fade trail",defaultValue:true},autoFade:{type:ControlType.Boolean,title:"Time fade",defaultValue:true},fadeDuration:{type:ControlType.Number,title:"Fade duration",defaultValue:2,min:.2,max:10,step:.1,hidden:p=>!p.autoFade},smoothing:{type:ControlType.Number,title:"Smoothing",defaultValue:.3,min:0,max:1,step:.05},dotSize:{type:ControlType.Number,title:"Dot size",defaultValue:6,min:2,max:20,hidden:p=>p.variant!=="dots"},dotSpacing:{type:ControlType.Number,title:"Spacing",defaultValue:10,min:5,max:40,hidden:p=>p.variant!=="dots"},particleCount:{type:ControlType.Number,title:"Particles",defaultValue:6,min:1,max:40,hidden:p=>p.variant!=="particles"},particleSize:{type:ControlType.Number,title:"Size",defaultValue:3,min:1,max:10,hidden:p=>p.variant!=="particles"},spreadAngle:{type:ControlType.Number,title:"Spread",defaultValue:30,min:0,max:180,hidden:p=>p.variant!=="particles"},drift:{type:ControlType.Number,title:"Drift",defaultValue:.4,min:-2,max:2,step:.1,hidden:p=>p.variant!=="particles"},pixelSize:{type:ControlType.Number,title:"Pixel size",defaultValue:6,min:2,max:24,hidden:p=>p.variant!=="pixel"},snapToGrid:{type:ControlType.Boolean,title:"Snap grid",defaultValue:true,hidden:p=>p.variant!=="pixel"},blendMode:{type:ControlType.Enum,title:"Blend mode",defaultValue:"source-over",options:["source-over","lighter","screen"],optionTitles:["Normal","Lighter","Screen"]}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"MouseTrail","slots":[],"annotations":{"framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Mouse_trail.map
